import "./globals.css";
import { Bebas_Neue, Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400','700'],
  variable: "--font-roboto",
})

const bebas = Bebas_Neue({
  subsets: ['latin'],
  weight: ['400'],
  variable: "--font-bebas",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bebas.variable} ${roboto.variable}`}>{children}</body>
    </html>
  );
}
